--- 
- hosts: "{{clusterName}}"
  remote_user: root
  connection: ssh
  gather_facts: yes
  vars:
    username: tperry
    HOST_COUNT: "{{ groups[clusterName] | length }}"
  tasks:
  - name: Install vsftpd
    # Install vsftp
    yum: 
      name: vsftpd
      state: latest
  - copy: content="There are {{ HOST_COUNT }} vms" dest=/tmp/hostcount
