--- 
- hosts: all
  remote_user: root
  connection: ssh
  gather_facts: yes
  vars:
    username: tperry
  tasks:
  - name: Install mlocate
    yum: 
      name: mlocate
      state: latest
    #notify:
    #- startservice
  #handlers:
  #- name: startservice
    #service:
      #name: httpd
      #state: restarted
