---

- name: 'Configure Disks - Windows'
  hosts: all
  tasks:
    - win_command: powershell.exe Get-Disk | Where partitionstyle -eq ‘raw’ | Initialize-Disk -PartitionStyle MBR -PassThru | New-Partition -AssignDriveLetter -UseMaximumSize | Format-Volume -FileSystem NTFS -Confirm:$false